settings:
  files:
    outputs:
      status: false
      path: ""
      name: .r.outputs.log
    logs:
      status: false
      path: ""
      name: .r.logs.log
    errors:
      status: false
      path: ""
      name: .r.errors.log
  legacy:
    force: false
    interval: 0s
server:
  status: false
  open: false
  port: 5001
  host: "localhost"
schema:
- name: STEAM
  path: .
  args:
#  - --pics
#  - --consumers
  commands:
    install:
      status: true
    build:
      status: false
    run:
      status: true
  watcher:
    paths:
    - /
    extensions:
    - go
    - yaml
    ignored_paths:
    - .git
    - vendor
    - node_modules
